# Generated by Django 3.1.3 on 2020-11-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_orders', '0004_auto_20201124_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_bill',
            field=models.CharField(default='', max_length=100),
        ),
    ]
