# Generated by Django 3.1.1 on 2020-10-08 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('actual_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('isFeatured', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 8, 6, 5, 43, 674943, tzinfo=utc))),
            ],
        ),
    ]
