# Generated by Django 3.1.1 on 2020-10-08 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('productDisplay', '0002_auto_20201008_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 6, 9, 36, 593020, tzinfo=utc)),
        ),
    ]
