# Generated by Django 3.1.1 on 2020-10-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productDisplay', '0005_auto_20201008_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isSpecial',
            field=models.BooleanField(default=False),
        ),
    ]
