# Generated by Django 3.1.1 on 2020-10-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productDisplay', '0006_product_isspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
