# Generated by Django 3.1.1 on 2020-10-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productDisplay', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
