# Generated by Django 3.1.3 on 2020-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productDisplay', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='', max_length=100),
        ),
    ]
