# Generated by Django 3.1.3 on 2020-11-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productDisplay', '0013_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
